cluster-config: "cluster_config.yml"
cluster: "qsub -V -lwalltime={cluster.time} -lselect={cluster.nodes}:ncpus={cluster.cpus}:mem={cluster.mem} -N {cluster.name} -o {cluster.logs} -e {cluster.logs}"
jobs: 50
resources: [cpus=100, mem_mb=320000]
latency-wait: 60
restart-times: 3
printshellcmds: True
use-conda: True
conda-frontend: "conda"
keep-going: True